# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShopApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'SDWebImage', '~> 4.0'
    pod 'Firebase/Core'
    pod 'TPKeyboardAvoidingSwift'
    pod 'CropViewController'
    pod 'RealmSwift'
    pod 'Fabric', '~> 1.9.0'
    pod 'Crashlytics', '~> 3.12.0'
    pod 'AMPopTip'

  # Pods for ShopApp

  target 'ShopAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShopAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
